Issue #6: Fetch pool data from camelot
open-dollar/od-sdk pull request #12
Opened 2023-09-14 21:32 UTC by jahabeebs

closes #6 

## Description
- I made this template for fetching the liquidity data (not price data yet) of OD and WETH in a pool. There still need to be some smart contract changes before this can be tested. 

Any problems in the logic?

2023-10-03 18:07 UTC, pi0neerpat requested changes
- Add `camelotPoolAddress` to the OD token object 0x2A09411c7208c6dDcEC0fe8e3E58841f5F0F2030 
- Add `chainlinkRelayer` to WETH token object 0x42d8a0Eb0dFE1b5b4A2631adBb3310aEa3d70a92
- Fetch balances of WETH and OD
- Use market price of OD
- Use ChainlinkRelayer `getResultWithValidity` for price of WETH
- calculate the USD price of each
- Add both to get total amount USD
- rename return variable to `totalLiquidityUSD`

2023-10-05 19:12 UTC, jahabeebs commented
> * Add `camelotPoolAddress` to the OD token object 0x2A09411c7208c6dDcEC0fe8e3E58841f5F0F2030
> 
>     * Add `chainlinkRelayer` to WETH token object 0x42d8a0Eb0dFE1b5b4A2631adBb3310aEa3d70a92
> 
>     * Fetch balances of WETH and OD
> 
>     * Use market price of OD
> 
>     * Use ChainlinkRelayer `getResultWithValidity` for price of WETH
> 
>     * calculate the USD price of each
> 
>     * Add both to get total amount USD
> 
>     * rename return variable to `totalLiquidityUSD`

made the changes, but blocked because fetching the market price of OD fails consistently (tried both geb.contracts.oracleRelayer.marketPrice() and geb.contracts.oracleRelayer.connect(geb.provider).marketPrice). I suppose I could call fetchAnalyticsData within fetchPoolData but that would be a lot of calls to our contracts when all we need is the OD price

2023-10-18 18:40 UTC, jahabeebs commented
@pi0neerpat I've verified that I can get the balance of OD and WETH from our sample pool, it formats these correctly into big numbers and returns the liquidity in USD as well

here's the response from the sdk function, used in the app (see console logs):

<img width="1468" alt="getting correct info" src="https://github.com/open-dollar/od-sdk/assets/47253537/0cd40c1c-ea00-4918-845b-5e8a6d4eb31f">

2023-10-19 17:49 UTC, pi0neerpat approved these changes

2023-10-19 18:05 UTC, merged